### ISSUE TITLE
你好作者，我这里有一些乱码的BUG想问一下

### ISSUE THREAD

**Issue by xxzhwl** [keel/bk#1]
希望能够获得一些帮助，就是命令窗口的中文选项都是乱码。

**Comment by keel** [comment]
不好意思, 才看到.

这是因为引用了一个readline-sync库会造成WINDOWS下中文乱码, 我这边发布了1.1.19版本,去掉了这个库,自己实现了相关功能. 

您可以升级到1.1.19版本, 再测试下.

**Comment by keel** [comment]
`npm update bk -g` 即可.
